using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AngleBracingPlugin.Modeler_Classes.Abstract_Classes;

// Tekla Structures Namespaces
using TSM = Tekla.Structures.Model;
using TSD = Tekla.Structures.Dialog;
using TSDT = Tekla.Structures.Datatype;
using T3D = Tekla.Structures.Geometry3d;
using TSMUI = Tekla.Structures.Model.UI;
using Tekla.Structures.Plugins;
using Tekla.Structures.Model.Operations;

namespace AngleBracingPlugin
{
    class AngleBolts : BoltModeler
    {
               


        public AngleBolts(double boltSize)
        {
            /*
            // Create new bolt array
            // Set default Values
            base.newBoltArray = new TSM.BoltArray();
            base.startPoint = new T3D.Point(0,0,0);
            base.endPoint = new T3D.Point(0, 0, 0);
            base.boltQuantity = 1;
            base.boltSize = boltSize;
            base.boltSpaceX = 0;
            base.boltSpaceY = 0;
            base.startOffsetX = 0;
            base.startOffsetY = 0;
            base.startOffsetZ = 0;
            base.cutLength = 150;
            base.boltStandard = "A325N";
            base.newBoltArray.Position.Plane = TSM.Position.PlaneEnum.MIDDLE;
            base.newBoltArray.Position.Plane = TSM.Position.RotationEnum.BELOW;
            base.newBoltArray.Position.Plane

    */
           
        }
    }
}
